/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedIntegracaoBlingRouteImport } from './routes/_authenticated/integracao-bling'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as ApiPublicHooksBlingSyncTickRouteImport } from './routes/api/public/hooks/bling-sync-tick'
import { Route as ApiPublicBlingCallbackRouteImport } from './routes/api/public/bling/callback'
import { Route as AuthenticatedAdminAdminSettingsRouteImport } from './routes/_authenticated/_admin/admin.settings'
import { Route as AuthenticatedAdminAdminClientsRouteImport } from './routes/_authenticated/_admin/admin.clients'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegracaoBlingRoute =
  AuthenticatedIntegracaoBlingRouteImport.update({
    id: '/integracao-bling',
    path: '/integracao-bling',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksBlingSyncTickRoute =
  ApiPublicHooksBlingSyncTickRouteImport.update({
    id: '/api/public/hooks/bling-sync-tick',
    path: '/api/public/hooks/bling-sync-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlingCallbackRoute = ApiPublicBlingCallbackRouteImport.update({
  id: '/api/public/bling/callback',
  path: '/api/public/bling/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminAdminSettingsRoute =
  AuthenticatedAdminAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdminClientsRoute =
  AuthenticatedAdminAdminClientsRouteImport.update({
    id: '/admin/clients',
    path: '/admin/clients',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integracao-bling': typeof AuthenticatedIntegracaoBlingRoute
  '/admin/clients': typeof AuthenticatedAdminAdminClientsRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/api/public/bling/callback': typeof ApiPublicBlingCallbackRoute
  '/api/public/hooks/bling-sync-tick': typeof ApiPublicHooksBlingSyncTickRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/integracao-bling': typeof AuthenticatedIntegracaoBlingRoute
  '/admin/clients': typeof AuthenticatedAdminAdminClientsRoute
  '/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/api/public/bling/callback': typeof ApiPublicBlingCallbackRoute
  '/api/public/hooks/bling-sync-tick': typeof ApiPublicHooksBlingSyncTickRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/integracao-bling': typeof AuthenticatedIntegracaoBlingRoute
  '/_authenticated/_admin/admin/clients': typeof AuthenticatedAdminAdminClientsRoute
  '/_authenticated/_admin/admin/settings': typeof AuthenticatedAdminAdminSettingsRoute
  '/api/public/bling/callback': typeof ApiPublicBlingCallbackRoute
  '/api/public/hooks/bling-sync-tick': typeof ApiPublicHooksBlingSyncTickRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agent'
    | '/dashboard'
    | '/integracao-bling'
    | '/admin/clients'
    | '/admin/settings'
    | '/api/public/bling/callback'
    | '/api/public/hooks/bling-sync-tick'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agent'
    | '/dashboard'
    | '/integracao-bling'
    | '/admin/clients'
    | '/admin/settings'
    | '/api/public/bling/callback'
    | '/api/public/hooks/bling-sync-tick'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/agent'
    | '/_authenticated/dashboard'
    | '/_authenticated/integracao-bling'
    | '/_authenticated/_admin/admin/clients'
    | '/_authenticated/_admin/admin/settings'
    | '/api/public/bling/callback'
    | '/api/public/hooks/bling-sync-tick'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBlingCallbackRoute: typeof ApiPublicBlingCallbackRoute
  ApiPublicHooksBlingSyncTickRoute: typeof ApiPublicHooksBlingSyncTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integracao-bling': {
      id: '/_authenticated/integracao-bling'
      path: '/integracao-bling'
      fullPath: '/integracao-bling'
      preLoaderRoute: typeof AuthenticatedIntegracaoBlingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/bling-sync-tick': {
      id: '/api/public/hooks/bling-sync-tick'
      path: '/api/public/hooks/bling-sync-tick'
      fullPath: '/api/public/hooks/bling-sync-tick'
      preLoaderRoute: typeof ApiPublicHooksBlingSyncTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bling/callback': {
      id: '/api/public/bling/callback'
      path: '/api/public/bling/callback'
      fullPath: '/api/public/bling/callback'
      preLoaderRoute: typeof ApiPublicBlingCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/admin/settings': {
      id: '/_authenticated/_admin/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/clients': {
      id: '/_authenticated/_admin/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AuthenticatedAdminAdminClientsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminClientsRoute: typeof AuthenticatedAdminAdminClientsRoute
  AuthenticatedAdminAdminSettingsRoute: typeof AuthenticatedAdminAdminSettingsRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminClientsRoute: AuthenticatedAdminAdminClientsRoute,
  AuthenticatedAdminAdminSettingsRoute: AuthenticatedAdminAdminSettingsRoute,
  AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntegracaoBlingRoute: typeof AuthenticatedIntegracaoBlingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntegracaoBlingRoute: AuthenticatedIntegracaoBlingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBlingCallbackRoute: ApiPublicBlingCallbackRoute,
  ApiPublicHooksBlingSyncTickRoute: ApiPublicHooksBlingSyncTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
